name: Deploy Serverless Application Model

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install SAM cli
      run: |
        pip3 install aws-sam-cli --upgrade

        echo "::add-path::$HOME/.local/bin"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Test with pytest
      run: |
        pip install pytest
        pip install boto3
        python -m pytest tests/ -v

    - name: Build SAM
      run: sam build

    - name: Deploy SAM
      run: sam deploy --stack-name visitor-counter-stack --region ap-southeast-1 --capabilities CAPABILITY_IAM --s3-bucket sam-cli-bucket-prod-ver --s3-prefix visitor-counter-stack --no-fail-on-empty-changeset
